export interface Medicine{
    medicineId: number,
    name: string,
	chemical: string,
	exp: string,
	mfg: string,
	qty: number,
	power: string,
	type: string,
	description: string,
	seller: string,
	brandName: string,
	price: number,
	url: string,
	category: string,
	categoryName: string,
}