let medicineList = [
  {
    "medicineId": "00000000-0000-0000-0000-000000000000",
    "name": "Johnson's Baby Powder",
    "chemical": "Sodium Citrate / Citric Acid",
    "exp": "07/2022",
    "mfg": "04/2019",
    "qty": 5,
    "power": "400 g",
    "type": "powder",
    "description": "Johnson's Baby Powder is a specially formulated talcum powder designed for the soft skin of your baby.",
    "seller": "JOHNSON'S Store",
    "brandName": "JOHNSON'S BABY",
    "price": 200.2,
    "url": "Powder.jpg",
    "category": "baby",
    "categoryName": "Baby Care"
  },
  {
    "medicineId": "00000000-0000-0000-0000-000000000000",
    "name": "Himalaya Baby care - Gift Pack (Set of 7)",
    "chemical": "Various Chemicals",
    "exp": "07/2022",
    "mfg": "04/2019",
    "qty": 4,
    "power": "510 g",
    "type": "combo",
    "description": "The products that are included in the baby gift pack will soothe, nourish and provide gentle care to your baby's skin.",
    "seller": "Jain & Brothers",
    "brandName": "Himalaya Herbs",
    "price": 495.0,
    "url": "Baby_Care.jpg",
    "category": "baby",
    "categoryName": "Baby Care"
  },
  {
    "medicineId": "00000000-0000-0000-0000-000000000000",
    "name": "Himalaya Guduchi Tablets",
    "chemical": "No Chemicals Used",
    "exp": "07/2022",
    "mfg": "04/2019",
    "qty": 6,
    "power": "250 mg",
    "type": "tablet",
    "description": "It is a health supplement and are created to be effective against fevers and other infective conditions, backed by Ayurveda and modern research.",
    "seller": "Jain & Brothers",
    "brandName": "Himalaya Pure Herbs",
    "price": 138.6,
    "url": "Guduchi_tablets.jpg",
    "category": "baby",
    "categoryName": "Baby Care"
  },
  {
    "medicineId": "00000000-0000-0000-0000-000000000000",
    "name": "Liveasy Baby Care Feeding Bottle",
    "chemical": "No Chemicals Used",
    "exp": "07/2022",
    "mfg": "04/2019",
    "qty": 3,
    "power": "250 ml",
    "type": "syrup",
    "description": "This bottle is specially designed for the convenience of feeding as evidenced in the slim neck and splendid body which helps with a firm and comfortable grip.",
    "seller": "MD Labs",
    "brandName": "LivEasy",
    "price": 199,
    "url": "Feeding_Bottle.jpg",
    "category": "baby",
    "categoryName": "Baby Care"
  },
  {
    "medicineId": "00000000-0000-0000-0000-000000000000",
    "name": "Merocrit Baby Injection",
    "chemical": "Meropenem",
    "exp": "07/2022",
    "mfg": "04/2019",
    "qty": 2,
    "power": "125 mg",
    "type": "injection",
    "description": "' It treats infections of various body parts like skin, soft tissues, blood, brain (meningitis), lungs (pneumonia), urinary tract.",
    "seller": "Aggarwal Medicose",
    "brandName": "Cipla Ltd",
    "price": 154,
    "url": "merocrit-injection.jpg",
    "category": "baby",
    "categoryName": "Baby Care"
  },
  {
    "medicineId": "00000000-0000-0000-0000-000000000000",
    "name": "Dexolac Special Care Infant Formula",
    "chemical": "Amino Acids",
    "exp": "07/2022",
    "mfg": "04/2019",
    "qty": 1,
    "power": "400 g",
    "type": "powder",
    "description": "' Dexolac Stage 1 Infant Formula is a powdered milk substitute for babies upto 6 months age. It contains nutrients that support overall growth & development.",
    "seller": "Aggarwal Medicose",
    "brandName": "Nutrica International Pvt Ltd",
    "price": 495,
    "url": "Dexolac.jpg",
    "category": "baby",
    "categoryName": "Baby Care"
  },
  {
    "medicineId": "00000000-0000-0000-0000-000000000000",
    "name": "Dolo 650mg Tablet 15'S",
    "chemical": "Acetaminophen",
    "exp": "07/2022",
    "mfg": "04/2019",
    "qty": 8,
    "power": "650 mg",
    "type": "tablet",
    "description": "Dolo is used to reduce fever and treat mild to moderate pain. Also, it is used to relieve headache, migraine, toothache, period pain, back pain, muscle pain and rheumatic pains.",
    "seller": "Aarx Pharmacy",
    "brandName": "Micro Labs Ltd",
    "price": 27,
    "url": "Dolo.jpg",
    "category": "general",
    "categoryName": "General Medicines"
  },
  {
    "medicineId": "00000000-0000-0000-0000-000000000000",
    "name": "Vomikind Fast Strip 4mg",
    "chemical": "Ondansetron",
    "exp": "07/2022",
    "mfg": "04/2019",
    "qty": 5,
    "power": "4 mg",
    "type": "tablet",
    "description": "Vomikind Fast Orally Disintegrating Strip is used to prevent and manage nausea and vomiting induced due to chemotherapy and radiotherapy.",
    "seller": "Aarx Pharmacy",
    "brandName": "Mankind Pharma Pvd Ltd",
    "price": 12,
    "url": "Vomikind.jpg",
    "category": "general",
    "categoryName": "General Medicines"
  },
  {
    "medicineId": "00000000-0000-0000-0000-000000000000",
    "name": "Patanjali Balm 10 gm",
    "chemical": "No Chemicals Used",
    "exp": "07/2022",
    "mfg": "04/2019",
    "qty": 3,
    "power": "10 g",
    "type": "Gel",
    "description": "Patanjali Ayurveda Balm contains Gandhpurataila, Pudina satva and Neelgiritaila. Patanjali Balm provides relief from head aches and pains..",
    "seller": "Yadav Medical Store",
    "brandName": "Patanjali Ayurved Ltd",
    "price": 24.5,
    "url": "Balm.jpg",
    "category": "general",
    "categoryName": "General Medicines"
  },
  {
    "medicineId": "00000000-0000-0000-0000-000000000000",
    "name": "Moov Spray Pain Relief Specialist 80 gm",
    "chemical": "No Chemicals Used",
    "exp": "07/2022",
    "mfg": "04/2019",
    "qty": 5,
    "power": "80 g",
    "type": "spray",
    "description": "It provides you fast and long lasting relief from muscle pain, neck pain and backache, inflammation, sprain, myositis, fibrositis and sciatica. It is a fast pain relief spray for frozen shoulder and body ache.",
    "seller": "Yadav Medical Store",
    "brandName": "Patanjali Ayurved Ltd",
    "price": 232,
    "url": "Moov.jpg",
    "category": "general",
    "categoryName": "General Medicines"
  },
  {
    "medicineId": "00000000-0000-0000-0000-000000000000",
    "name": "Buscogast Tablet 10's",
    "chemical": "Hyoscine Butylbromide",
    "exp": "07/2022",
    "mfg": "04/2019",
    "qty": 5,
    "power": "10 mg",
    "type": "tablet",
    "description": "Buscogast 10 mg Tablet is also used to treat symptoms such as abdominal pain, bloating, indigestion, stomach cramps, diarrhoea, etc.",
    "seller": "Om Medical Agency",
    "brandName": "Sanofi India Limited",
    "price": 34.88,
    "url": "Buscogast.jpg",
    "category": "general",
    "categoryName": "General Medicines"
  },
  {
    "medicineId": "00000000-0000-0000-0000-000000000000",
    "name": "Torex Cough Syrup 100ml",
    "chemical": "Ammonium Chloride",
    "exp": "07/2022",
    "mfg": "04/2019",
    "qty": 5,
    "power": "100 ml",
    "type": "syrup",
    "description": "Torex Cough syrup is a combination medicine used to treat cough. It thins the mucus in the nose and windpipe, making it easier to cough out.",
    "seller": "Om Medical Agency",
    "brandName": "Torque Pharmaceuticals Pvt Ltd",
    "price": 94.4,
    "url": "Torex.jpg",
    "category": "general",
    "categoryName": "General Medicines"
  },
  {
    "medicineId": "00000000-0000-0000-0000-000000000000",
    "name": "Dermadew Soap, 75 gm",
    "chemical": "Sodium Chloride, Titanium Dioxide",
    "exp": "07/2022",
    "mfg": "04/2019",
    "qty": 4,
    "power": "75 g",
    "type": "soap",
    "description": "Dermadew soap moisturizers the skin and also be used to prevent or reduce acne, dermatitis, itching or dry skin. It effectively removes dead skin cells and dirt away from the body.",
    "seller": "Fortis Healthworld Store",
    "brandName": "Hegde & Hegde Pharmaceutica Llp",
    "price": 128,
    "url": "Soap.jpg",
    "category": "skin",
    "categoryName": "Skin Care"
  },
  {
    "medicineId": "00000000-0000-0000-0000-000000000000",
    "name": "Betadine 10% Ointment",
    "chemical": "Povidone Iodine",
    "exp": "07/2022",
    "mfg": "04/2019",
    "qty": 3,
    "power": "20 g",
    "type": "gel",
    "description": "It is used for the treatment and prevention of infections in wounds and cuts. It kills the harmful microbes and controls their growth, thereby preventing infections in the affected area.",
    "seller": "Fortis Healthworld Store",
    "brandName": "Win-Medicare Pvt Ltd",
    "price": 113,
    "url": "Betadine.jpg",
    "category": "skin",
    "categoryName": "Skin Care"
  },
  {
    "medicineId": "00000000-0000-0000-0000-000000000000",
    "name": "Himalaya Purifying Neem Face Pack 100 gm",
    "chemical": "No Chemicals Used",
    "exp": "07/2022",
    "mfg": "04/2019",
    "qty": 5,
    "power": "100 g",
    "type": "cream",
    "description": "Himalaya's purifying Neem Pack brings together the goodness of Neem, Fuller's Earth and Turmeric, which work together to regulate excess oil secretion, clean clogged pores and prevent the recurrence of pimples.",
    "seller": "Divine Pharmacy",
    "brandName": "Himalaya Herbs",
    "price": 91.8,
    "url": "Facewash.jpg",
    "category": "skin",
    "categoryName": "Skin Care"
  },
  {
    "medicineId": "00000000-0000-0000-0000-000000000000",
    "name": "Ring Out Dusting Powder 65gm",
    "chemical": "Clotrimazole",
    "exp": "07/2022",
    "mfg": "04/2019",
    "qty": 4,
    "power": "65 g",
    "type": "powder",
    "description": "Ring Out dusting Powder is a topical antifungal medicine that is used to prevent or treat fungal infections of the skin. It helps in relieving associated symptoms like rashes, itching in intimate bod parts, etc. ",
    "seller": "Divine Pharmacy",
    "brandName": "Mankind Pharmaceuticals Ltd",
    "price": 69.5,
    "url": "Ring-Out.jpg",
    "category": "skin",
    "categoryName": "Skin Care"
  },
  {
    "medicineId": "00000000-0000-0000-0000-000000000000",
    "name": "Everherb Neem - Immunity Booster",
    "chemical": "No Chemicals Used",
    "exp": "07/2022",
    "mfg": "04/2019",
    "qty": 7,
    "power": "250 mg",
    "type": "capsule",
    "description": "It is an excellent blood purifier. It removes toxins from the body and cleanses the blood which supports healthy skin. ",
    "seller": "Ambika Medicose",
    "brandName": "EverHerb",
    "price": 455.24,
    "url": "Neem.jpg",
    "category": "skin",
    "categoryName": "Skin Care"
  },
  {
    "medicineId": "00000000-0000-0000-0000-000000000000",
    "name": "Complex Vitamins & Minerals Daily Vital 60 Tablets",
    "chemical": "Musclexp Zinc",
    "exp": "07/2022",
    "mfg": "04/2019",
    "qty": 100,
    "power": "1 for 180mg",
    "type": "tablet",
    "description": "MuscleXP Men daily Sports Multivitamin Tablets are packed with a powerful blend of amino acids that work together to help promote protein synthesis,",
    "seller": "MuscleXP",
    "brandName": "MuscleXP",
    "price": 890,
    "url": "ZincComplex.webp",
    "category": "vitamin",
    "categoryName": "Vitamins"
  },
  {
    "medicineId": "00000000-0000-0000-0000-000000000000",
    "name": "Wellman Health Supplement",
    "chemical": "Antioxidants and Essential Micronutrients",
    "exp": "07/2022",
    "mfg": "04/2019",
    "qty": 30,
    "power": "1 for 100mg",
    "type": "tablet",
    "description": "Wellman health supplement has been developed to help maintain general",
    "seller": "Wellman",
    "brandName": "WELLMAN",
    "price": 665,
    "url": "Vitamintablets.webp",
    "category": "vitamin",
    "categoryName": "Vitamins"
  },
  {
    "medicineId": "00000000-0000-0000-0000-000000000000",
    "name": "Vitamin C Combo Pack -Hair,Skin& Nails",
    "chemical": "Carbamide Forte L Glutathione",
    "exp": "07/2022",
    "mfg": "04/2019",
    "qty": 30,
    "power": "1tab for 150mg",
    "type": "tablet",
    "description": "LIGHTER SKIN WITH MELANIN REDUCTION: Glutathione pills may help fight melanin production and thus clear dark spots,",
    "seller": "FORTE",
    "brandName": "CARBAMIDE FORTE",
    "price": 560,
    "url": "Carbamide.webp",
    "category": "vitamin",
    "categoryName": "Vitamins"
  },
  {
    "medicineId": "00000000-0000-0000-0000-000000000000",
    "name": "Himalaya Guduchi",
    "chemical": "Guduchi Stem Extract",
    "exp": "07/2022",
    "mfg": "04/2019",
    "qty": 30,
    "power": "1 for 150mg",
    "type": "tablet",
    "description": "Guduchi tablets is a health supplemenr andare created to be effective against fevers and other infective .",
    "seller": "Himalaya",
    "brandName": "Himalaya",
    "price": 260,
    "url": "Guduchi.webp",
    "category": "vitamin",
    "categoryName": "Vitamins"
  },


// ==================================== Tesing Arrays till here =========================
  {
    "medicineId": "00000000-0000-0000-0000-000000000000",
    "name": "Green Coffee Bean",
    "chemical": "Natural Herbals",
    "exp": "07/2022",
    "mfg": "04/2019",
    "qty": 60,
    "power": "1cap for 200mg",
    "type": "capsule",
    "description": "WOW Life science Green Coffee Bean Extract Dietary Supplement is formulated to assist with safe weight management. ",
    "seller": "Wow",
    "brandName": "WOW LIFE SCIENCE",
    "price": 760,
    "url": "Greencoffenvitamin.webp",
    "category": "vitamin",
    "categoryName": "Vitamins"
  },
  {
    "medicineId": "00000000-0000-0000-0000-000000000000",
    "name": "Chau Foods Cardamom Value Pack 100 g Green Eilachi  (100 g)",
    "chemical": "Natural Cardamom",
    "exp": "07/2022",
    "mfg": "04/2019",
    "qty": 10,
    "power": "100 g Green Eilachi in 1 packet",
    "type": "powder",
    "description": "Special to Indian taste buds, green cardamom which is also known as ",
    "seller": "Chau",
    "brandName": "CHAU FOODS",
    "price": 160,
    "url": "chau.webp",
    "category": "vitamin",
    "categoryName": "Vitamins"
  },

// ========================== To be Added 1 bty one =========================
  {
    "medicineId": "00000000-0000-0000-0000-000000000000",
    "name": "Sanitizer",
    "chemical": "Ethyl-Hexadecyl-Dimethyl Ammonium Ethysulphate 0.2 g",
    "exp": "07/2022",
    "mfg": "04/2019",
    "qty": 100,
    "power": "Take 2 dip for hygiene",
    "type": "liquid",
    "description": "Handrub® is an alcohol-based instant hand sanitizer. Alcohol hand rub kills 99.99% of a broad range of bacteria include.",
    "seller": "Microwin",
    "brandName": "Microwin",
    "price": 320,
    "url": "Sanitizer.jpg",
    "category": "surgical",
    "categoryName": "Surgical items"
  },
  {
    "medicineId": "00000000-0000-0000-0000-000000000000",
    "name": "Boldfit Surgical Mask (Pack Of 50)",
    "chemical": "Pure Cotton used",
    "exp": "One time usable",
    "mfg": "06/2017",
    "qty": 0,
    "power": "Use & Throw",
    "type": "Surgical cover",
    "description": "Disposable Mask With Nose Pin 3 Ply Face Mask. Make yourself safe by using this multinose pin .",
    "seller": "Boldfit",
    "brandName": "Boldfit",
    "price": 320,
    "url": "Mask.jpg",
    "category": "surgical",
    "categoryName": "Surgical items"
  },


// --------------------------- To be added from Angular API testing ------------------------



  {
    "medicineId": "00000000-0000-0000-0000-000000000000",
    "name": "Prozo Plus Fingertip Pulse Oximeter",
    "chemical": "Hard Metal Used",
    "exp": "",
    "mfg": "06/2017",
    "qty": 50,
    "power": "Multicolour",
    "type": "surgical",
    "description": "The pulse oximeter, or Pulse Ox, is an electronic device that measures the oxygen level",
    "seller": "Prozo",
    "brandName": "Prozo Distribution",
    "price": 1080,
    "url": "oximeter.jpg",
    "category": "surgical",
    "categoryName": "Surgical items"
  },
  {
    "medicineId": "00000000-0000-0000-0000-000000000000",
    "name": "InfektoCide Aktiv Professional Disinfectant & Cleaner Liquid for Surfaces 5 Litre",
    "chemical": "Ethanol Cover",
    "exp": "07/2022",
    "mfg": "04/2019",
    "qty": 100,
    "power": "5 Log Reduction of Micro-organisms: Kills 99.999%",
    "type": "liquid",
    "description": "One Step medical Grade Disinfectant &amp; Cleaner that can be used for both mopping and wiping Hard Surfaces and also in sprayer/fogger.",
    "seller": "Aktiv",
    "brandName": "Aktiv",
    "price": 620,
    "url": "aktiv.jpg",
    "category": "surgical",
    "categoryName": "Surgical items"
  },
  {
    "medicineId": "00000000-0000-0000-0000-000000000000",
    "name": "Covifind (Covid-19) Antigen Self Test Kit",
    "chemical": "Original",
    "exp": "07/2022",
    "mfg": "04/2019",
    "qty": 50,
    "power": "3 times usable",
    "type": "S item",
    "description": "Its used for self personal care health test kit related to covid-19.",
    "seller": "Covifind",
    "brandName": "Covifind",
    "price": 720,
    "url": "Covidtestkit.jpg",
    "category": "surgical",
    "categoryName": "Surgical items"
  },
  {
    "medicineId": "00000000-0000-0000-0000-000000000000",
    "name": "Omron Compressor Nebulizer",
    "chemical": "NE-C101",
    "exp": "07/2022",
    "mfg": "04/2019",
    "qty": 25,
    "power": "Double liquids inhaler",
    "type": "Surgical",
    "description": "",
    "seller": "Omron",
    "brandName": "Omron",
    "price": 1320,
    "url": "Nebulizer.jpg",
    "category": "surgical",
    "categoryName": "Surgical items"
  },
  {
    "medicineId": "00000000-0000-0000-0000-000000000000",
    "name": "Wash Proof Adhesive Bandages, 8 Count",
    "chemical": "Benzalkonium Chloride",
    "exp": "07/2022",
    "mfg": "04/2019",
    "qty": 12,
    "power": "8 s",
    "type": "surgical",
    "description": "Adhesive Bandages is designed to protect the Wound and Scab from Friction, Bacteria, Damage, and Dirt. This making the healing process of the wound fast and safe. ",
    "seller": "Ambika Medicose",
    "brandName": "Apollo Hospitals Enterprise Ltd",
    "price": 20,
    "url": "Bandage.jpg",
    "category": "surgical",
    "categoryName": "Surgical Items"
  },
];
